- name: Promote main to prod
  env:
    GH_PAT: ${{ secrets.GH_PAT }}
  run: |
    git fetch origin
    git checkout prod
    git merge origin/main --no-edit

    # ✅ Set remote to use PAT
    git remote set-url origin https://x-access-token:$GH_PAT@github.com/${{ github.repository }}.git

    # ✅ Push to prod
    git push origin prod
