name: Promote main to prod

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false # ✅ Disable default bot token

      - name: Set up Git identity
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Promote main to prod
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "Using repository: ${{ github.repository }}"

          git fetch origin

          # Switch to prod or create it
          if git show-ref --quiet refs/heads/prod; then
            git checkout prod
          else
            git checkout -b prod origin/prod
          fi

          # Merge main into prod
          git merge origin/main --no-edit

          # ✅ Overwrite the remote to use personal token
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}

          # Debug: show remotes
          git remote -v

          # ✅ Push to prod
          git push origin prod
