name: Promote main to prod

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false # ✅ Disable default bot token

      - name: Set up Git identity
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Promote main to prod
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git fetch origin
          if git show-ref --quiet refs/heads/prod; then
            git checkout prod
          else
            git checkout -b prod origin/prod
          fi
          git merge origin/main --no-edit
      
          # ✅ Correct remote using fully expanded Bash variables
          git remote set-url origin https://x-access-token:$GH_PAT@github.com/${GITHUB_REPOSITORY}.git
          git push origin prod
