name: Promote main to prod

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Promote main to prod
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "Repo: ${{ github.repository }}"
          echo "Token length: ${#GH_PAT}"

          git fetch origin

          # Checkout prod
          if git show-ref --quiet refs/heads/prod; then
            git checkout prod
          else
            git checkout -b prod origin/prod
          fi

          git merge origin/main --no-edit

          # 🔥 Set authenticated remote with token injected into the URL
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git

          git push origin prod
